### PR TITLE
Document and enforce `JWT` `payload` type to be either `String` or `Map<String, dynamic>`

### LINKED ISSUE #67: Type payload as `Map<String, dynamic>`
I wonder why the `JWT.payload` is typed as `dynamic` instead of `Map<String, dynamic>`, since a Map is used when a token is created with this library and a `Map` is also needed when the token needs to be validated.

In my understanding the current implementation of `JWT.decode` would just throw on anything but a `Map`.  
Because even though there is the fallback in the `catch` block, the result of `utf8.decode` is always `String` and thus the `payload['iss']` access would throw.

From https://github.com/jonasroussel/dart_jsonwebtoken/blob/main/lib/src/jwt.dart#L202-L211
```dart
      dynamic payload;

      try {
        payload = jsonBase64.decode(base64Padded(parts[1]));
      } catch (ex) {
        payload = utf8.decode(base64Url.decode(base64Padded(parts[1])));
      }

      final audiance = _parseAud(payload['aud']);
      final issuer = payload['iss']?.toString();
```

Similarly `JWT.verify` seemingly supports `String` payloads as per

https://github.com/jonasroussel/dart_jsonwebtoken/blob/main/lib/src/jwt.dart#L62
```
        payload = utf8.decode(base64Url.decode(base64Padded(parts[1])));
```

But then it does not do any validation, even if `checkExpiresIn` or `checkNotBefore` are given. (Just like all the other possible checks are ignored, so e.g. if you pass a `subject` parameter and expect this to throw in case none is found, if there is a `String` payload with a valid signature that message would just succeed.)

So the way I see it, the current `dynamic payload` would crash in the first example, and lead to undesirable behavior in the second.

If there is really a use-case for the second part, we could extra the signature validation into a helper that one could use with arbitrary `String` payloads, but without suggestions that we got a valid JWT body matching all parameters.

Let me know what you think, happy to put up a PR for any of these changes 🤗

### PR DESCRIPTION
**Pull request by tp**
- Since https://github.com/jonasroussel/dart_jsonwebtoken/pull/68 was rejected, this needs to be enforced for both the constructor and the field setter
- You'll see that we copy/convert the `Map`s to `Map<String, dynamic>`, this has 2 reasons
  - For some literal maps (e.g. in the test cases, but also likely application code), we would get `Map<String, String>` (for example), so we need to convert those for the doc comments to be correct
  - Given the previous point, I thought it would be confusing if we only converted maps other than the "desired" `Map<String, dynamic>`, as some would then stay "in sync" with the original map (if it was ever changed) and some would not. (That's why https://github.com/jonasroussel/dart_jsonwebtoken/pull/68 also made them read-only, to bring any such late modifications to attention and err.)

Closes #67

### CODE REVIEW

File: lib/src/jwt.dart [hunk 1]
```diff
@@ -194,18 +205,15 @@ class JWT {
...
-      try {
-        payload = jsonBase64.decode(base64Padded(parts[1]));
-      } catch (ex) {
-        payload = utf8.decode(base64Url.decode(base64Padded(parts[1])));
-      }
+      final payload =
+          (jsonBase64.decode(base64Padded(parts[1])) as Map<String, dynamic>);
 
       final audiance = _parseAud(payload['aud']);
       final issuer = payload['iss']?.toString();
```
Comment (tp) [inline lib/src/jwt.dart:219]: Here, any non-`Map` payload would've failed anyway.

File: lib/src/jwt.dart [hunk 2]
```diff
@@ -281,7 +307,8 @@ class JWT {
     bool noIssueAt = false,
   }) {
     try {
-      if (payload is Map<String, dynamic> || payload is Map<dynamic, dynamic>) {
+      var payload = this.payload;
+      if (payload is Map<String, dynamic>) {
         try {
           payload = Map<String, dynamic>.from(payload);
```
Comment (tp) [inline lib/src/jwt.dart:313]: I think it made sense that this was taking a copy of the map (as it might've been immutable or used again in the previous variant which was not holding it's own copy), but I wonder if the "writing back" to `payload` was intentional?

Now we don't write back to the JWT object (`this`) (and the local reference is also needed to get the type checking work properly, as it's now based on Object instead of the "always working" `dynamic`).

**Comment by tp** [comment]
@ahmednfwela Sorry I missed that, even though we explicitly tried to contain the changes… But migrating away from `dynamic` I didn't think how correct but type-unchecked code could break here (in the samples and our project code we always type-check it as a `Map` first before accessing it).

Then we might as well go for a fully type-safe route and move away from `Object = String or Map` as it was in 3.3.0.
